
<div CLASS="clsNavigationMenu">

               <A href="./index.html" target="_top"> 
                    Home</A> 
               <br />
               <br />

               <A href="./mission.html" target="_top"> 
                    Mission statement</A>  
               <br />
               <A href="./collaboration.html" target="_top"> 
                    GENIE collaboration</A> 
               <br />
               <A href="./policy.html" target="_top"> 
                    Policy documents</A>
               <br />
               <A href="./copyright.html" target="_top"> 
                    Copyright notices</A>
               <br />
               <A href="./citing.html" target="_top"> 
                    Citing GENIE</A>  
               <br />
               <A href="./logos.html">  
                    Logos</A> 
               <br />
               <br />

               <A href="./releases.html"> 
                   <b>Public releases</b> </A>  
               <br />
               <A href="./tunes.html"> 
                   <b>Global fits & physics tunes</b> </A>
               <br />
               <A href="./naming_conventions.html"> 
                   Release and tune naming </A>
               <br />
               <br />
               <A href="./incubator.html"> 
                    Project incubator</A> 

               <br />
               <br />

               <A href="https://genie-docdb.pp.rl.ac.uk/cgi-bin/ShowDocument?docid=2" target="_top">
                 Physics&nbsp;&amp;&nbsp;user&nbsp;manual</A>
               <br />
               <A href="https://genie-docdb.pp.rl.ac.uk/cgi-bin/private/DocumentDatabase/" target="_top"> 
                  Document database</A> 
                  <img src="./images/icons/lock.png" align="top" height="15"> 
               <br />
               <br />
<!--
               <br />
               <A href="./load.php?include=pub"> Publications</A> <br />
-->

               <A href="https://geniemc.slack.com" target="_top"> 
                   Slack workspace</A> 
                  <img src="./images/icons/lock.png" align="top" height="15"> 
               <br />
               <br />

               <A href="https://www.jiscmail.ac.uk/cgi-bin/webadmin?A0=NEUTRINO-MC-SUPPORT" target="_top"> 
                   User mailing list</A> 
               <br /> 
               <A href="https://www.jiscmail.ac.uk/cgi-bin/webadmin?A0=NEUTRINO-MC-CORE" target="_top">    
                   Developer mailing list</A> 

               <br />   
               <br />   

               <A href="https://github.com/GENIE-MC" target="_top">   
                   GitHub organization page</A> 
               <br />
               <A href="https://github.com/GENIE-MC/Generator" target="_top"> 
                   [Generator repository]</A>  
               <br />
               <A href="https://github.com/GENIE-MC/Comparisons" target="_top"> 
                   [Comparisons repository]</A> 
                   <img src="./images/icons/lock.png" align="top" height="15">  
               <br />
               <A href="https://github.com/GENIE-MC/Tuning" target="_top"> 
                   [Tuning repository]</A> 
                   <img src="./images/icons/lock.png" align="top" height="15"> 
               <br />
               <br />


               <A href="./get_started.html">  
                    Get started </A>          
               <br />
               Generator doxygen
               <br />
               GENIE course
               <br />
               <br />

               <A href="./news.html" target="_top"> 
                    News</A> 
               <br />

</div>
